# Generated by Django 5.2.8 on 2025-11-22 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(help_text='Total number of equipment entries')),
                ('avg_flowrate', models.FloatField(help_text='Average flowrate across all equipment')),
                ('avg_pressure', models.FloatField(help_text='Average pressure across all equipment')),
                ('avg_temperature', models.FloatField(help_text='Average temperature across all equipment')),
                ('type_distribution', models.JSONField(help_text='Distribution of equipment types')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw CSV data in JSON format', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dataset History',
                'verbose_name_plural': 'Dataset Histories',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
