# Generated by Django 5.2.8 on 2025-11-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasethistory',
            name='equipment_types_count',
            field=models.IntegerField(default=0, help_text='Number of unique equipment types'),
        ),
        migrations.AddField(
            model_name='datasethistory',
            name='ranges',
            field=models.JSONField(default=dict, help_text='Min/Max/StdDev ranges for parameters'),
        ),
        migrations.AddField(
            model_name='datasethistory',
            name='type_wise_breakdown',
            field=models.JSONField(default=dict, help_text='Statistics broken down by equipment type'),
        ),
    ]
