# Generated by Django 5.2.8 on 2025-11-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datasethistory_equipment_types_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasethistory',
            name='ml_metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Machine learning model metrics', null=True),
        ),
    ]
